### ISSUE TITLE
eos_bgp resource module

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/arista.eos#71]

**Comment by sc68cal** [comment]
Is the plan to import https://github.com/arista-eosplus/ansible-eos-bgp ? Because I've used that module heavily and would prefer that we pull that module in, compared to writing a brand new one - since I've used the replacements for `eos_l2_interface` and `eos_linkagg` and found bugs in them. We should be working to improve existing, not making new and creating new bugs
